name: 'Hello World Docker Action'
description: 'Says hello world using docker actions'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
    time:
      description: 'The time we said hello'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - - ${{ inputs.who-to-greet }}
